
import { AlumniProfile, Interaction, ChatMessage } from '../types';
import { parseAlumniCSV } from '../utils/csvParser';

const ALUMNI_KEY = 'alumniconnect_profiles';
const INTERACTIONS_KEY = 'alumniconnect_interactions';
const CHAT_HISTORY_KEY = 'alumniconnect_chat_history';

// Full dataset from data/alumni.csv
const CSV_CONTENT = `"Name","Headline","Location","Company","Company industry","Last updated"
"Amber Coniff","Principal at Twin Peaks Charter Academy","Denver, CO","Twin Peaks Charter Academy","-","1/26/2026"
"Ryan Frost","Senior Analyst at The Walt Disney Company","Los Angeles Metropolitan Area","The Walt Disney Company","Entertainment","1/26/2026"
"Chloe Tomlinson","Criminology & Sociolegal Studies Student | University of Denver","Denver, CO","Cedar Kids","-","1/26/2026"
"drew pullin","Student at University of Denver","Chester, CT","-","-","1/26/2026"
"Sydney Sharp","Business Development","Los Angeles Metropolitan Area","3thix","Financial Services","1/26/2026"
"Jeremy Kogan","Aspiring Global Business Leader with a focus on Real Estate Finance","Denver, CO","Foundry Commercial","Real Estate","1/26/2026"
"Kai Sato","Registered Behavior Technician","Denver, CO","Soar Autism Center","Hospital & Health Care","1/26/2026"
"Peyton Schumacher","Student at University of Denver","Denver, CO","-","-","1/26/2026"
"Ed Lenhart","Owner/President at JCI Construction LLC","Grand Junction, CO","JCI Construction LLC","Construction","1/26/2026"
"Liam Connors","Student athlete at the University of Denver","Denver, CO","LXTC Lacrosse Training Center","Sports","1/26/2026"
"Scarlett Metz","Rising junior at the University of Denver","United States","A Little Help (ALH)","Non-profit Organization Management","1/26/2026"
"Catie Moynahan","Biochemistry Student at the University of Denver","Denver, CO","Crocs, Inc.","Apparel & Fashion","1/26/2026"
"Antonio Collins","Co-Owner of Small Businesses","Denver Metropolitan Area","United Plumbing Services Company","Construction","1/26/2026"
"Finley Tucker","Student at University of Denver","Denver, CO","-","-","1/26/2026"
"Sarah Krohn","Environmental Science and Honors student at the University of Denver","Denver, CO","University of Denver - Sturm College of Law","Higher Education","1/26/2026"
"Ronald Munkittrick","MBA Candidate |","Denver, CO","Intrinsic LLC","Financial Services","1/26/2026"
"Eli Throop","Graduate of the University of Denver - Burns School of Real Estate & Construction Management","Denver, CO","Concrete Frame Associates, LLC","Construction","1/26/2026"
"Emma Schaben","English Language Assistant","Denver, CO","NALCAP","Education Management","1/26/2026"
"Justin Lu","Associate Software Engineer | L3Harris Technologies","Colorado Springs, CO","L3Harris Technologies","Defense & Space","1/26/2026"
"Luke Milburn","Student at University of Denver","Denver, CO","NORTHWEST INVESTMENT MANAGEMENT, INC.","Real Estate","1/26/2026"
"Gabriel Nelson","IT Operations","Denver, CO","HomeSafe","-","1/26/2026"
"Ben Nalen","Accounting Manager - Consolidated Resource and L&L Fabrication","Denver, CO","Consolidated Resource, LLC","Oil & Energy","1/26/2026"
"June Steingass","Marketing and Journalism student at the University of Denver","Denver, CO","Delta Gamma","Higher Education","1/26/2026"
"Jack McDonald","Daniels College of Business","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Iruka Nwosu","Student at University of Denver","Denver, CO","University of Denver - Daniels College of Business","Higher Education","1/26/2026"
"Ioanna Tsanai","Software Developer","United States","Global Payments Inc.","Financial Services","1/26/2026"
"Mackenzie Bonner","Recreation","Denver, CO","Town of Parker, Colorado","Government Administration","1/26/2026"
"Delaney McGowan","Student at University of Denver","Denver, CO","Chipotle Mexican Grill","Restaurants","1/26/2026"
"Skylar Stewart","Recent graduate from the University of Denver","Mill Valley, CA","Monster Energy","Food & Beverages","1/26/2026"
"Luke Shinofield","Student Athlete at The University of Denver | Finance Major at The Daniels College of Business","Virginia Beach, VA","Atlantic Coast Mortgage","Financial Services","1/26/2026"
"Corey LaScala","Marketing Major at the University of Denver","Denver, CO","LE DOCK","Restaurants","1/26/2026"
"Ari Klotas","Student at University of Denver","Aurora, CO","-","-","1/26/2026"
"Jake Hunter","Business Solutions Analyst","Denver, CO","Sekisui House U.S., Inc.","Construction","1/26/2026"
"Sophie Carnoali","Marketing Manager at Fathom Entertainment","Denver, CO","Fathom Entertainment","Entertainment","1/26/2026"
"Lauren Fuller","Graduate Student at the University of Denver","Denver, CO","Plante Moran","Accounting","1/26/2026"
"Riley Kristjanson","Software Engineer at Paylocity","Denver Metropolitan Area","Paylocity","Computer Software","1/26/2026"
"Shively Kerek","Biology and Psychology Student at University of Denver","Denver, CO","Intermountain Health","Hospital & Health Care","1/26/2026"
"Kathryn Getter","Founder of Recover at Home: In-home eating disorder support and coaching","Denver Metropolitan Area","Recover at Home","-","1/26/2026"
"Patrick Zhang","Business Manager @ NGA Fleet Tech |","Denver, CO","NGA Fleet Tech","-","1/26/2026"
"Nora Johnson","University of Denver","Denver, CO","Philip dabney law firm","-","1/26/2026"
"Alyssa Miragliotta","Internal Communications Assistant at Pax8","Denver, CO","Pax8","Computer Software","1/26/2026"
"Ted Dayton","University of Denver, Class of 2024. Daniels College of Business.","Denver, CO","Boone Caps","-","1/26/2026"
"Emily Lewis","Graduate student at Adler University in Chicago IL.","Denver, CO","MotherWise Colorado","Individual & Family Services","1/26/2026"
"Holden Heidt","Finance Major at the University of Denver - Daniels College of Business | Minor in Leadership | Pre-Law Student","Denver, CO","University of Denver- Men's Club Soccer","-","1/26/2026"
"Ella Witherite","Graduate Student at the University of Denver | Future Nonprofit Leader Committed to Positive Change | Community Liaison at Autism West Behavior Partners | President of Starting Block Foundation","Denver, CO","Autism West Behavior Partners","Individual & Family Services","1/26/2026"
"Hector Rodriguez","AI Consulting Analyst at Accenture | Daniels Fund Scholar","Denver Metropolitan Area","University of Denver - Ritchie School of Engineering & Computer Science","Higher Education","1/26/2026"
"Griffin Williams","University of Denver","Denver, CO","Koi Business Solutions","-","1/26/2026"
"Joseph O'Toole","Economics and Public Policy | Honors Student at University of Denver","Denver, CO","City of Sacramento","Government Administration","1/26/2026"
"Dr.Meghana G.","Security/IT Enthusiast Seeking IT Roles | MS-IT (INFOSEC) at the University of Denver | ISACA Mentee | Content Writer | Dentist","Aurora, CO","WiCyS DU","Higher Education","1/26/2026"
"Manikanta Revuri","Software Engineer - AI/ML | Ex-Amazon | Ex-Juspay","Parker, CO","Caterpillar Inc.","Machinery","1/26/2026"
"Aansha Sankla","University of Denver Alumna Class of 2024","Denver Metropolitan Area","The Club at Las Campanas","Hospitality","1/26/2026"
"Brenda Villegas","Student at University of Denver","Denver, CO","University of Colorado Anschutz","Higher Education","1/26/2026"
"Aidan Semelsberger","Student Athlete (Soccer) and Fourth Year Accounting Student at the University of Denver.","Denver, CO","Los Alamos National Laboratory","Research","1/26/2026"
"Kyle Huwaldt","Associate Analyst @ Spectrum | Musician | Athlete","Denver, CO","Spectrum Business for enterprise","Telecommunications","1/26/2026"
"Niall Doherty","BA Environmental Science graduate from the University of Denver.","Portland, OR","Kenai-Red Fish Company","Food & Beverages","1/26/2026"
"Lina Hurley","Student at The University of Denver","Needham, MA","Boston Ski + Tennis","Retail","1/26/2026"
"Meghan Angley","Reporter and Host covering the NHL for Guerilla Sports","Denver, CO","Guerilla Sports","Online Media","1/26/2026"
"Tim McKelvey","Project Engineer at Vertix Builders","Denver, CO","Vertix Builders, Inc.","Construction","1/26/2026"
"Ryan Laughlin","Hospitality Management Major | Cook at Knoebel Events","Denver, CO","Knoebel Events","-","1/26/2026"
"Feruz Yahia","Strategic Communications Student at University of Denver","Denver, CO","Undergraduate Student Government - University of Denver","Education Management","1/26/2026"
"Gavin Neils","Regulatory Auditor | Tax Compliance","Denver, CO","State of Missouri","Government Administration","1/26/2026"
"Jeslyn Zheng","4th year Accounting student at the University of Denver - Daniels College of Business | Minoring in Chinese","Denver, CO","Alpha Phi International Fraternity","Non-profit Organization Management","1/26/2026"
"Callie Monroe","Staff Software Engineer at Vantor","Thornton, CO","Vantor","Computer Software","1/26/2026"
"Sidney Stark","Recent graduate from the University of Denver","United States","Griffiths Law PC","Law Practice","1/26/2026"
"Bradford Roberts","Recruiting & Operations Professional","New York, NY","Chapter","Computer Software","1/26/2026"
"Jack Zanone","Student at University of Denver","Denver, CO","La Plata Communities, Inc.","Real Estate","1/26/2026"
"Justin Marciano","PSM","Denver Metropolitan Area","-","-","1/26/2026"
"Mia Collins","Student at University of Denver","Denver Metropolitan Area","Hillstone Restaurant Group","Restaurants","1/26/2026"
"Sydney Kaster","Marketing and Health Sciences | University of Denver | Class of 2026","Denver, CO","Tactile Medical","Medical Device","1/26/2026"
"Anthony Michael","Sales","Denver, CO","Unemployed at this time","Higher Education","1/26/2026"
"Christian Horvath","Finance Club President @ DU | Finance Student | CFA Candidate | Trading, Portfolio Strategy, Asset Management | Former Schwab Intern (Tax Ops)","Bedford, NY","University of Denver Finance Club","-","1/26/2026"
"Bitseit Kebede","Associate Business Analyst at Vantage Data Centers | B.S Computer Science at the University of Denver","Denver, CO","Vantage Data Centers","Information Technology & Services","1/26/2026"
"Katherine Calixto","Accounting Student at Daniels College of Business","Denver, CO","Community Commons","-","1/26/2026"
"Enoch Asimbisa","Assistant to the dean of students at Kwame Nkrumah' University of Science and Technology, Kumasi","United States","University of Denver","Higher Education","1/26/2026"
"Tia Sciarrotta","Digital and Social Marketing Specialist with MARVIN Magazine","Denver, CO","Marvin Media LLC","Media Production","1/26/2026"
"Ryan Green","BS in Accounting & Master of Accountancy Candidate | University of Denver Daniels College of Business | Class of 2027","Denver, CO","EY","Information Technology & Services","1/26/2026"
"Reese Pratt","Student at University of Denver","Denver, CO","Tavern In the Village","Restaurants","1/26/2026"
"Max Adelstein","Real estate major at University of Denver, class 2026","North Kingstown, RI","metal dynamics","-","1/26/2026"
"Oliver Banks","Business Student at the University of Wisconsin-Madison","Northbrook, IL","State Street Brats","Restaurants","1/26/2026"
"Sean Perman","PHD Student at the University of Denver","Denver, CO","IPS Strategic Capital","Financial Services","1/26/2026"
"Riley Justice","International Studies and Language University of Denver Graduate","Denver, CO","Ecole nationale du Génie de l'Eau et de l'Environnement de Strasbourg","Higher Education","1/26/2026"
"Brandon Chapman","Aspiring CPA; Currently a student at the University of Denver, pursuing a bachelors in accounting and a Master of Science in Accounting, Technology and Analytics. Former D1 Swimmer.","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Erin Kenney","Accounting Student at University of Denver - Daniels College of Business","Denver, CO","RubinBrown LLP","Accounting","1/26/2026"
"Giuliana Ziliotto","MSATA Student at the University of Denver | BS Business Information & Analytics","Denver, CO","PwC","Information Technology & Services","1/26/2026"
"Tyler Brunet","Data Analyst with a focus on systems and reporting","Denver, CO","Caraluzzi's Markets","Supermarkets","1/26/2026"
"Catie Bryant","Youth Fine Arts Coordinator & Marketing Manager at Evanston Art Center","Chicago, IL","Evanston Art Center","Arts & Crafts","1/26/2026"
"Sarah Fishbein","Biology Major at the University of Denver","Minneapolis, MN","Breck School","Education Management","1/26/2026"
"Maija Graham","Student at University of Denver","Denver, CO","Bollier Ciccone Stinson LLP","Law Practice","1/26/2026"
"Zane Shami","Mechanical engineering student at the University of Denver.","United States","University of Denver Time Attack Racing Team","Sports","1/26/2026"
"Cooper Gastrock","Sophomore at University of Denver | Daniels College of Business | Finance and German","Denver, CO","Bright Road Wealth Management, LLC","Financial Services","1/26/2026"
"Zoe Schaab","Student at University of Denver - Daniels College of Business - Studying Marketing and working on expanding my education further","Denver Metropolitan Area","MOR Kombucha","Food Production","1/26/2026"
"Steven Said","Mechanical Engineer with a Master of Science Concentrating on Biomechanics and Medical Device Development","Denver, CO","University of Denver - Ritchie School of Engineering & Computer Science","Higher Education","1/26/2026"
"Tara O’Brien","Psychology and Socio-Legal Studies Student at the University of Denver","Winnetka, IL","The HomeMore Project","Non-profit Organization Management","1/26/2026"
"Luke Holden","Business student at University of Denver Daniels School of Business","Orinda, CA","University of Denver","Higher Education","1/26/2026"
"Jefferson Downes","Undergrad at the University of Denver studying Computer Engineering","Denver, CO","-","-","1/26/2026"
"Jack Gould","4th year student at the University of Denver | Major in Emergent Digital Practices | Beta Theta Pi Alpha Zeta Chapter","United States","The Town Club","-","1/26/2026"
"Grace Wander","Accounting student at the University of Denver | Daniel’s College of Business | Class of 2027 | Accounting Major, Spanish Minor | Passion for Volunteering, Sustainability, and Business | Hard-working | Optimistic","Minnetonka, MN","Private family","Education Management","1/26/2026"
"Mac O'Brien","Red Bull Student Marketeer","Denver, CO","Red Bull","Food & Beverages","1/26/2026"
"Rhys Jones","University of Denver - Daniels College of Business - Finance Major pursuing Math and Computer Science Minor","Denver, CO","IPS Strategic Capital","Financial Services","1/26/2026"
"Maggie Kruse","Economic Public Policy and Criminology Undergraduate Student at the University of Denver","United States","DU Sales Club","Publishing","1/26/2026"
"Henry Sullivan","Mechanical Engineering Student at University of Denver","Denver, CO","Hit The Net Sports","Consumer Goods","1/26/2026"
"Andreas Kirkeng","Business Analyst DU Alumni - Master in Applied Quantitative Finance","Denver, CO","Prosmar","Information Technology & Services","1/26/2026"
"Skylar Jacobs","Computer Science Student at University of Denver","Littleton, CO","Target","Retail","1/26/2026"
"Jacob Turner","Student at University of Denver","Littleton, CO","Pedalheads","Health, Wellness & Fitness","1/26/2026"
"Ethan Peltier","Student at University of Denver, CO","St Paul, MN","Loyal Marymount University","-","1/26/2026"
"Charles Johnson","Student at University of Denver","Watertown, NY","Morgia Wealth Management","Financial Services","1/26/2026"
"Luke Boyer","University of Denver student majoring in hospitality.","Denver, CO","-","-","1/26/2026"
"Gigi Lombardi","Marketing Student at University of Denver - Daniels College of Business","Greater Boston","Deckers Brands","Apparel & Fashion","1/26/2026"
"Evan Chamberlain","Psychology and Kinesiology student at the University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Benjamin Block","Student and Employee at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Lilou Cabrol","International Studies and Environmental Science (B.A.) double Major, with minors in Leadership and Sustainability at the University of Denver","Denver, CO","Rocky Mountain Splash Artistic Swimming","Sports","1/26/2026"
"Mallory Rogers","Anthropology Graduate from University of Denver","United States","Tripepi Smith","Marketing & Advertising","1/26/2026"
"Marley Flanagan","Undergraduate Student at the University of Denver | B.A in Political Science and Journalism Studies | Aspiring Law Student","United States","University of Denver","Higher Education","1/26/2026"
"Dakotah Parker","Student-Athlete at University of Denver - Daniels School of Business Marketing Major","Denver, CO","Monticello Schools Extracurricular Activities","-","1/26/2026"
"Iris Stanfill","Recent graduate from the University of Denver with a BA in Political Science","Denver Metropolitan Area","New Leaf Hearing Clinic","-","1/26/2026"
"Andrew French","Business Information and Analytics | Daniel’s College of Business ‘26 |","Denver, CO","DU Sports Analytics Lab","-","1/26/2026"
"Ben Trookman","Research associate in IBD at Cedars Sinai University of Denver 2024 Pre-med BS: Physiology in health and disease Triple minor in Medical physics, Human Health Sciences, and Chemistry","Los Angeles, CA","Cedars-Sinai","Hospital & Health Care","1/26/2026"
"Delaney Mullen","Political Science & Socio-Legal Studies Student at the University of Denver","Broomfield, CO","Mendocino Farms","Restaurants","1/26/2026"
"Nolan Patrick","Management Student | University of Denver | Aspiring Innovator with a Passion for Technology, Strategy & Growth","Parker, CO","Zayo Global Reach","Telecommunications","1/26/2026"
"Elizabeth Duffie","International Studies & Public Policy Student at University of Denver","Denver, CO","Delta Gamma","Higher Education","1/26/2026"
"Laine Satterlee","Accounting Student at the University of Denver | Daniels College of Business","Denver, CO","Castle Pines Golf Club","Hospitality","1/26/2026"
"Drew Collins","Mechanical Engineering Student at University of Denver","Denver, CO","Lowe's Companies, Inc.","Retail","1/26/2026"
"Colin Roderick","Junior | Burns School of Real Estate in Construction Management | University of Denver","Denver, CO","UtilityBI","Computer Software","1/26/2026"
"Lilli D’Agostino","Experienced in social media, marketing, and sales strategies.","Swampscott, MA","ADP","Human Resources","1/26/2026"
"Amrit Samra","Student at University of Denver","Brighton, CO","-","-","1/26/2026"
"Teagan Weindel","Public Policy & International Studies Student at the University of Denver | Leadership Studies Minor | PLP Leadership Studies Program","Denver, CO","Perfect Pair","Non-profit Organization Management","1/26/2026"
"Jack Dougan","International Studies and Political Science student at the University of Denver","Herndon, VA","New York State Assembly","Legislative Office","1/26/2026"
"Alicia Sharun","Accounting Student pursuing a MAcc and a BSAcc at the University of Denver","Denver, CO","Nutrien Ag Solutions","Farming","1/26/2026"
"CJ Schlegel","University of Denver Construction Management student, minoring in Finance, pursuing a career in Construction Management","Bethesda, MD","CBG Building Company","Construction","1/26/2026"
"Owen Hart","Accounting Student | Aspiring CPA | Interested in Assurance, Tax, Financial Analysis & Advisory","Denver, CO","Wojcicki & Mulroe, P.C.","Accounting","1/26/2026"
"Liz Woxland","Student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Charlie Jennings","International Studies Student at the University of Denver","Denver, CO","Frederick S. Pardee Institute for International Futures","Research","1/26/2026"
"Daniel Stevinson","Business Information and Analytics Major | Marketing Minor | Student at University of Denver | Class of 2026","Denver, CO","Ball Corporation","Packaging & Containers","1/26/2026"
"Harley Fulford","Psychology and Criminology student at the University of Denver","Denver Metropolitan Area","Gamma Phi Beta International Sorority","Non-profit Organization Management","1/26/2026"
"Gabriella Sramek","Finance and Business Information & Analytics Student at University of Denver","Denver, CO","Delta Sigma Pi - Alpha Nu Chapter","Higher Education","1/26/2026"
"Sama Abdulameer","Honors Student at University of Denver | Colorado Women’s Leadership Scholar | International Affairs and Business Ethics and Legal Studies | Pre-Law","Denver Metropolitan Area","University of Denver - Josef Korbel School of Global and Public Affairs","Higher Education","1/26/2026"
"Lea Bridgeman","Student at The University of Denver","Denver, CO","Gamma Phi Beta International Sorority","Non-profit Organization Management","1/26/2026"
"Frederick Lotuff","Student at University of Denver","Denver, CO","-","-","1/26/2026"
"Ella Korman","Student at University of Denver","Glenview, IL","Forza","-","1/26/2026"
"Megan Cunningham","Hospitality Management Student at The University of Denver","Denver, CO","CorePower Yoga","Health, Wellness & Fitness","1/26/2026"
"Christine Jordan","Hospitality Management | Food & Beverage","Aurora, CO","Ignite Reading","Education Management","1/26/2026"
"Peyton Cunningham","Software Engineer, Recent Graduate, University of Denver, University of Colorado Boulder","Parker, CO","Movement","Health, Wellness & Fitness","1/26/2026"
"Cade Berman","Analyst | Python • SQL • BI","Denver, CO","Gaming Laboratories International, LLC","Gambling & Casinos","1/26/2026"
"Sarah Hutchings","International Studies and Music Student at University of Denver","Denver, CO","Strategic Kids","Education Management","1/26/2026"
"Josie LeCompte","Aspiring Sports Professional | Student at the University of Denver","Denver, CO","DU Clarion","Media Production","1/26/2026"
"Kaila Hendershot","Student at the University of Denver | Marketing Major | Passionate about Creativity through Reading and Painting | Committed to Driving Innovative Marketing Solutions","Denver, CO","The Peaks, A Senior Living Community","Hospital & Health Care","1/26/2026"
"Liam Dee","International Relations major at the University of Denver","United States","University of Denver","Higher Education","1/26/2026"
"Kiara Nagle, FPQP","Student at the University of Denver, Daniels College of Business, Reiman School of Finance, MS Applied Quantitative Finance, BSBA Finance & Minor in Accounting","Denver, CO","UBS","Financial Services","1/26/2026"
"Ethan Jacobson","Real Estate Finance @ DU | Passionate about development and building new environments","Denver, CO","PCL Construction","Construction","1/26/2026"
"Saeed Mohamed","NSBE Digital Coordinator | Computer Science and Mathematics at the University of Denver","Denver Metropolitan Area","University of Denver","Higher Education","1/26/2026"
"Ellen Kaufman","Finding innovative and efficient ways to solve problems","Denver, CO","Cox Automotive Inc.","Computer Software","1/26/2026"
"Lauren Zimmerman","Accounting Manager at Aduro Advisors","Denver, CO","Aduro Advisors","Financial Services","1/26/2026"
"Case Davis","Business Operations Lead at Playground","Denver, CO","Playground","Computer Software","1/26/2026"
"Ethan Krumholz","Student at University of Denver","Denver, CO","RubinBrown LLP","Accounting","1/26/2026"
"Randi Keller","Sr. Manager, Redwoods Leadership Program","Englewood, CO","DaVita Kidney Care","Hospital & Health Care","1/26/2026"
"Anna Rosenberger","Student athlete at University of Denver | Business management major","Glenview, IL","NCAA","Higher Education","1/26/2026"
"Benjamin Pineda","Senior Technology Leader | Software Engineering | Application Development | DevSecOps | Cattle Rancher","Denver Metropolitan Area","BAE Systems, Inc.","Defense & Space","1/26/2026"
"Vanessa García, MLS","Policy Analyst at Gary Community Ventures","Denver Metropolitan Area","Gary Community Ventures","Philanthropy","1/26/2026"
"Ian MacLeod","Finance major & Entrepreneurship minor","Denver, CO","Bigelow LLC","Investment Banking","1/26/2026"
"Caroline (Lewis) Jackson, CFP","Senior Wealth Strategy Associate","Denver, CO","UBS","Financial Services","1/26/2026"
"Shane McGrath","Student at University of Denver","Denver, CO","-","-","1/26/2026"
"Ella Greene","University of Denver | Business Analytics | Criminology | Aspiring Intelligence & National Security Professional","Denver, CO","Eva Gates Homemade Preserves","Food & Beverages","1/26/2026"
"Hannah Lane","Property Manager at Ascentia Real Estate Holding Company","Littleton, CO","Littleton Public Schools","Primary/Secondary Education","1/26/2026"
"Evan Mora","Senior Software Engineer at Engrain | Expertise in Software Infrastructure","Broomfield, CO","Engrain","Computer Software","1/26/2026"
"Bryn Posey","Marketing | Financial Planning | Event Planning | Leadership | Staff Training & Development | MBA Candidate","Walnut Creek, CA","Saint Mary's College of California","Higher Education","1/26/2026"
"Julian Goodman","Multi-Award-Winning Documentarian as well as Marketing Leader","Denver, CO","College of Professional Studies at University of Denver","Higher Education","1/26/2026"
"Tara Stanley","University of Denver - Daniels College of Business - Finance - Construction Management","Denver, CO","PCL Construction","Construction","1/26/2026"
"Emerson House","Analyst at Revelation Pharma LLC","Denver Metropolitan Area","Revelation Pharma","Pharmaceuticals","1/26/2026"
"Sarayu Pakala","Data Analyst at Denver Health","Aurora, CO","Denver Health","Hospital & Health Care","1/26/2026"
"Annie Knapp","Marketing Coordinator at Exclusive Resorts | University of Denver Alumni","Denver, CO","Exclusive Resorts","Hospitality","1/26/2026"
"Megan Doherty","Business Management Student at University of Denver | Pioneer Leadership Program","Natick, MA","Charles River Country Club","Recreational Facilities & Services","1/26/2026"
"Willem DeValk","Financial Analyst at Bison Oil & Gas | University of Denver Alumni - BSBA in Finance | Founder of Valk Vehicle Advisory","Denver, CO","Bison Oil & Gas IV, LLC","Oil & Energy","1/26/2026"
"Catherine Albertson","Student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Bright Mleta","Program Coordinator- Student Engagement","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Riley Trippe","Student at the University of Denver | Sociology & Psychology Major | Master's in Social Work","Denver, CO","Pearpop","Marketing & Advertising","1/26/2026"
"Liam McGuire","Political Science and International Studies Student at University of Denver","Denver, CO","MOUNT VERNON COUNTRY CLUB","Hospitality","1/26/2026"
"Eliana Schwade","Recent graduate from the University of Denver","United States","Hillel of Colorado","Religious Institutions","1/26/2026"
"Gabriella Antonini","Operations Associate at Feals","Denver, CO","Feals","Consumer Goods","1/26/2026"
"Cody Brosh","Graduate from University of Denver","Denver, CO","5280 Burger Bar","Food & Beverages","1/26/2026"
"Luca Boyle","Finance at the University of Denver","Denver, CO","Focal Point Capital","Venture Capital & Private Equity","1/26/2026"
"Hamza Lakhani","Student at University of Denver","Denver, CO","Engro Corporation","Events Services","1/26/2026"
"Amelia Katz","Student in Daniels College of Business at University of Denver","Denver, CO","-","-","1/26/2026"
"Sanjay Rao","Data science @ University of Denver | Data Engineering, Big Data, Machine Learning, Statistical Analysis, Data Mining","Denver, CO","Community Dreams Foundation","Management Consulting","1/26/2026"
"Brianna Florence","Passionate Pre-Med student aspiring to make a change in underserved communities","Aurora, CO","ScribeAmerica","Hospital & Health Care","1/26/2026"
"Nico Morton","Student Athlete at the University of Denver","Denver, CO","Jeremy Ranch Country Club","-","1/26/2026"
"Grace Creamer","Assurance Staff at Plante Moran","Denver, CO","Plante Moran","Accounting","1/26/2026"
"Ellie Pessah","Incoming Audit Associate at BDO","Denver, CO","BDO","Accounting","1/26/2026"
"Emma Hoffman","SDR at ORS Nasco | University of Denver Alumni | B.S. in Accounting","Denver, CO","ORS Nasco","Wholesale","1/26/2026"
"Grace Chovil","Mission-Oriented, Interdisciplinary, Curious","Denver, CO","Colorado Parks and Wildlife","Government Administration","1/26/2026"
"Jackson Kyhl","Disposition Agent at New Western","Denver, CO","New Western","Real Estate","1/26/2026"
"Will Ottley","Student at University of Denver","Atlanta Metropolitan Area","Chick-fil-A Restaurants","Restaurants","1/26/2026"
"Finn Soderstrom","Undergraduate student studying Business Information and Analytics at the University of Denver","Denver, CO","Sweet Ginger","Food Production","1/26/2026"
"Abigail Hallam","Customer Success Coordinator | Insite Analytics","Englewood, CO","Riddell","Retail","1/26/2026"
"Hari Udayyar","Graduate Research Assistant @ University of Denver | Bioengineering, Biomedical Engineering","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Casiah Smith","Community Event Organizer","Denver, CO","Colorado Black Round Table","-","1/26/2026"
"Mic Kelly","Professional Lacrosse Player","Towson, MD","Premier Lacrosse League","Sports","1/26/2026"
"Brooklynn Cardenas","Finance Major | Business Information & Analytics Minor at University of Denver","Denver, CO","-","-","1/26/2026"
"Estrella Damian","Executive Assistant to the Director of Communications & Community Engagement at Denver Public Library","Denver, CO","Denver Public Library","Libraries","1/26/2026"
"Clara Chbat","Class of 2026 | Business Informatics and Analytics major | Advanced Excel","Denver, CO","Ballast Point Construction Inc","Construction","1/26/2026"
"Claire Westergren","Analyst at Millennium Bridge Capital | MBA","Denver, CO","Millennium Bridge Capital","Financial Services","1/26/2026"
"Anneliese Rempe","Marketing & Communications Analyst at Gates Corporation","Denver, CO","-","-","1/26/2026"
"Aidan McNally","Student at University of Denver studying Political Science and Public Policy","Denver, CO","Phillip Romero for Westminster Colorado","-","1/26/2026"
"Aven McCall","Student at University of Denver || Boettcher Scholar 2023","Denver, CO","Sticky Fingers Cooking","Education Management","1/26/2026"
"Soma Shekar","MS Health Informatics @University of Denver | Clinical Research Coordinator | Pharm-D Graduate | Healthcare Data Analytics","Aurora, CO","UCHealth","Hospital & Health Care","1/26/2026"
"Isabella Villalobos","Marketing Admin Assistant at Tom’s Watch Bar","Denver, CO","Tom's Watch Bar","Restaurants","1/26/2026"
"Mya Horne","Biomedical Engineering at the University of Southern California","San Diego, CA","YMCA of the USA","Non-profit Organization Management","1/26/2026"
"Holly Hillstrom","Student at the University of Denver","Carmel, CA","-","-","1/26/2026"
"Sophia Forcier","University of Denver Graduate","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Katie Mittelstadt","Student at University of Denver","Denver, CO","Adventure Rock, Inc.","Health, Wellness & Fitness","1/26/2026"
"Faida Bea","Business Management Major","Denver, CO","Sigma Iota Epsilon","Management Consulting","1/26/2026"
"Norah Shamin","Economics and International Studies student at University of Denver","Littleton, CO","Frederick S. Pardee Institute for International Futures","Research","1/26/2026"
"Hudson Cramer","Associate Broker at Unique Properties, Inc","Denver Metropolitan Area","Unique Properties, Inc","Real Estate","1/26/2026"
"Alex Guylay","Student at University of Denver","Denver, CO","Encore","Events Services","1/26/2026"
"Grace Fowler","Merchandising Sales Leader, Pepsico Denver","Denver, CO","PepsiCo","Food & Beverages","1/26/2026"
"Richard Hensley","Service-Oriented Operations Leader | Data-Driven Problem Solver | Customer Experience Innovator","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Sergio Rodriguez","Student at University of Denver","Denver, CO","Milliman","Management Consulting","1/26/2026"
"Claire Patterson","Pursuing a BA at the University of Denver, Korbel School of International Studies.","Denver, CO","Carters Inc.","Apparel & Fashion","1/26/2026"
"Jordin Letchinger","Student at University of Denver","Denver, CO","Gust Elementary School","Real Estate","1/26/2026"
"Sophia Ferretti","Student","Sammamish, WA","University of Denver","Higher Education","1/26/2026"
"Adam Rosvold","Student at the University of Denver Daniel’s College of Business","Minneapolis, MN","Sigma Chi Fraternity","Civic & Social Organization","1/26/2026"
"Mehboob Hussain","Software Engineer intern | University of Denver | React, HTML, JavaScript, API Integration, QA Testing | Reliable Web Apps","Aurora, CO","Lady Fatima Center","-","1/26/2026"
"Scott Duffy","Real Estate and the Built Environment Major with a Concentration in Construction Project Management at the University of Denver","Denver, CO","United Contractor Services, LLC","Construction","1/26/2026"
"Zoë Stelzer","Lockheed Martin","Denver, CO","Lockheed Martin","Defense & Space","1/26/2026"
"Thomas Bahmandeji","Computer Science and Mathematics Student at DU","Denver, CO","University of Denver - Ritchie School of Engineering & Computer Science","Higher Education","1/26/2026"
"Devon Evenson","Student at the University of Denver | Accounting Major in the Daniels College of Business","Denver, CO","KPMG US","Financial Services","1/26/2026"
"Julia Atwood","Criminology and Socio-Legal Studies Student at University of Denver | Pre-Law track","Denver, CO","New Student and Family Planning at the University of Denver","-","1/26/2026"
"George Wilkins","Finance and Real Estate Student at the University of Denver","Wilmette, IL","Smith and Jones Shrinking Homes","-","1/26/2026"
"Lily Haverstock","Marketing and Communications Manager","Denver, CO","SPKN - The Sport Professional Knowledge Network","Higher Education","1/26/2026"
"Joshua Kerimo","Student at University of Denver","Denver, CO","-","-","1/26/2026"
"Luke Mitchell","Banking Officer at FirstBank","Denver, CO","FirstBank","Banking","1/26/2026"
"Cal O'Sullivan","Psychology Major | Assistant Teacher | Student at the University of Denver","Greater Boston","University of Denver","Higher Education","1/26/2026"
"Yazzy Simons","Computer Science Student at University of Denver","Denver, CO","Lucid Devices","-","1/26/2026"
"Charles Blanthorn","Accounting student at University of Denver, Daniels College of Business","Denver, CO","EisnerAmper","Accounting","1/26/2026"
"Rien Eckrich","Raytheon CLDP | University of Denver Graduate","Littleton, CO","Raytheon","Defense & Space","1/26/2026"
"Zachary Hughes","Marketing Solutions - Graduate Student | Writer, Project Manager, Photographer","Broomfield, CO","University of Denver","Higher Education","1/26/2026"
"Ivy Newman","Senior Mechanical Engineering Student at the University of Denver.","Denver, CO","Tri Delta","Non-profit Organization Management","1/26/2026"
"Garrett O'Brien","Analyst at J.P. Morgan - Equipment Syndications","United States","J.P. Morgan","Financial Services","1/26/2026"
"Jonah Kelley","Branch On Call Associate","Denver, CO","Edward Jones","Financial Services","1/26/2026"
"Olivia Sinnett","Social Media Communications Coordinator","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Sadie Roy","Psychology, Spanish, and Sociology Student at DU.","Minneapolis, MN","Warren Village","Non-profit Organization Management","1/26/2026"
"Dayanara Bustos","Real Estate Built Development Major | Business Information & Analytics Minor at Daniels College of Business","Denver, CO","Old Navy","Retail","1/26/2026"
"Timothy McFarland","Student at University of Denver","Denver, CO","1800GotJunk","-","1/26/2026"
"Danielle Thomas","P.S.M in Biomedical Sciences Student at the University of Denver","Denver, CO","Children's Hospital Colorado","Hospital & Health Care","1/26/2026"
"Luke Schultz","Student-Athlete at University of Denver","Denver, CO","-","-","1/26/2026"
"Andrew Sanchez","Student at University of Denver","Denver, CO","Five Guys Enterprises","Restaurants","1/26/2026"
"Lucy Kien","Systems Support Specialist | Computer Science Graduate","Longmont, CO","FieldSync Technologies","Telecommunications","1/26/2026"
"Ben Krajewski","Student at the University of Denver, President - Men’s Club Soccer team, Co-President - Pre-Dental Society. I plan on attending dental school and am interested in community betterment and impact.","Denver, CO","RPM Parking Companies, Inc.","Events Services","1/26/2026"
"Elijah Mereness","Assistant Project Manager Community Planning","Denver, CO","Toll Brothers","Real Estate","1/26/2026"
"Charlotte Stromberg","Marketing Major | Emergent Digital Practices Minor","Denver, CO","Volo Sports","Sports","1/26/2026"
"Christian Navarro","Accounting Student","Denver, CO","Argus Event Staffing LLC","Entertainment","1/26/2026"
"Achisa Panichakul","Biological Sciences and Psychology Student","Aurora, CO","University of Denver","Higher Education","1/26/2026"
"Grayson Gatrell","Masters in Accountancy Student","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Gavin Hailey","Senior Platform Engineer","Denver, CO","Ibotta","Computer Software","1/26/2026"
"Natalie Kadel","Sales Administrative Assistant","Glenview, IL","Hyatt","Hospitality","1/26/2026"
"Shemar Magee","LPCC | Self-Published Author","Denver, CO","Community Reach Center","Mental Health Care","1/26/2026"
"Zachary Headley","Operations Professional | Dual Masters Student","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Heath Ballard","Accounting Student | Aspiring CPA","Greater Chicago Area","KPMG US","Financial Services","1/26/2026"
"Lizzie Lesoing","Undergraduate Psychology & Business Student | Class of 2027","Lincoln, NE","University of Denver","Higher Education","1/26/2026"
"kira nikolaus","Business Information & Analytics Student","Denver, CO","Jacks on Pearl","-","1/26/2026"
"Kyle Waggoner","Technology Assurance Senior | Data Intelligence & Delivery","Denver, CO","EY","Information Technology & Services","1/26/2026"
"Chrysten Pacheco","J.D. Candidate | Former Student Athlete","Longmont, CO","McCabe Law","Law Practice","1/26/2026"
"Mounika Tatikonda","Clinical Applications Specialist | Healthcare Data Analyst","Aurora, CO","Colorado Blood Cancer Institute Medical Group","Hospital & Health Care","1/26/2026"
"Justin Cook","Associate | Real Estate & Construction Management","Denver, CO","Echelon Energy","Real Estate","1/26/2026"
"Naomi Mleta","Resident Director","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Samantha Henderson","Security Operations Representative | Applied Computing","Denver, CO","Wells Fargo","Financial Services","1/26/2026"
"Ashlyn Garvis","International Business Student | Spanish Minor","Minneapolis, MN","Xcel Energy","Utilities","1/26/2026"
"Carly Courtney","Hospitality Management Student | Class of 2026","Denver, CO","Fritz Knoebel School of Hospitality Management","Hospitality","1/26/2026"
"Megan Shaull","Marketing Analyst","Denver, CO","Major Tom Productions","Computer Software","1/26/2026"
"Benjamin Rushford","Field Engineer","Denver, CO","HENSEL PHELPS","Construction","1/26/2026"
"Maddie Welton","Psychology & Spanish Student","Denver, CO","Fortunato Management","-","1/26/2026"
"Kyle Hammond","Accounting Student | Finance Minor","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Katherine Gagner","Double BA Socio-Legal Studies & Public Policy","Denver, CO","Wilhelmina Rocky Mountains","Entertainment","1/26/2026"
"Bryce Willoughby","Student Athlete | Accounting Major","Denver, CO","Game Time Events","Sports","1/26/2026"
"Krystle Douby Compere","Assistant Field Manager Intern","Denver, CO","Shea Homes","Real Estate","1/26/2026"
"Charles Jacobs","Hospitality Professional","Denver, CO","Vail Resorts","Hospitality","1/26/2026"
"Noura Ali Abid","International Business Major | Japanese Minor","Littleton, CO","University of Denver","Higher Education","1/26/2026"
"Kragen Wild","Computer Science Student","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Dylan Kane","MPP Candidate","Denver, CO","Phil Weiser for Colorado","Political Organization","1/26/2026"
"Genevieve Springsteen","Biological Sciences Graduate","Denver, CO","Children's Hospital Colorado","Hospital & Health Care","1/26/2026"
"Tony Bisimwa","Cybersecurity Engineer | ECDLP Associate","Aurora, CO","United Airlines","Airlines/Aviation","1/26/2026"
"Grace Ha","Insurance Producer","Englewood, CO","Chungsoo Ha Farmers Insurance and Financial Services","Insurance","1/26/2026"
"Ella Caine","Business Development Specialist","Boise, ID","Idaho Housing and Finance Association","Financial Services","1/26/2026"
"Olivia Kachulis","JD Candidate | Environmental Science Graduate","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Xander Verity","MS Applied Quantitative Finance Candidate | CFA Level I","Denver, CO","Strategic Finance Inc","Financial Services","1/26/2026"
"Cole Joubert","Finance & Real Estate Student","Denver, CO","ABCO Electrical Construction & Design","Construction","1/26/2026"
"Dakota Johnson","Land Technician","Denver, CO","TCO Land & Regulatory","Oil & Energy","1/26/2026"
"Connor Orille","FBI Honors Intern | Aspiring Software Developer","Denver, CO","Federal Bureau of Investigation (FBI)","Law Enforcement","1/26/2026"
"Flynn Opstad","Student at University of Denver","Minneapolis, MN","Clune Construction Company","Construction","1/26/2026"
"Emily Anderson","Psychology & Communications Student","Minnetonka, MN","Alpha Phi International Fraternity","Non-profit Organization Management","1/26/2026"
"Daniel Lange","TA Coordinator | Microsoft Office Specialist","Denver, CO","University of Denver - Daniels College of Business","Higher Education","1/26/2026"
"Ellie Sinclair","Junior Software Developer","Denver Metropolitan Area","Hyve Health","Information Technology & Services","1/26/2026"
"Giordan Gulati","Business student at the University of Denver | Business owner of GulatiArt LLC","East Greenwich, RI","Pro Ambitions Hockey, Inc.","Sports","1/26/2026"
"Kayla Nguyen","Biochemistry Graduate | Aspiring Medical Student","Denver, CO","University of Colorado Anschutz School of Medicine","Higher Education","1/26/2026"
"Dylan Hecht","Studying psychology and biology","San Rafael, CA","Williams-Sonoma, Inc.","Retail","1/26/2026"
"Fiona Koshy","Brand Strategist","Denver, CO","Cactus","Marketing & Advertising","1/26/2026"
"Nate Sanders","Economics Student at University of Denver","Denver, CO","Cape","Computer Software","1/26/2026"
"Ned Forbush","Student Athlete at University of Denver","Denver, CO","Inside Lacrosse","Publishing","1/26/2026"
"Audrey Gutierrez","Master of Accountancy Student | Aspiring CPA","Denver, CO","Plante Moran","Accounting","1/26/2026"
"Shalom Abioye","Student at University of Denver","Denver, CO","Target","Retail","1/26/2026"
"Isabella Lorenz","B.S. in Biology and Psychology","Denver, CO","[solidcore]","Health, Wellness & Fitness","1/26/2026"
"Michaella Berkowitz","Client Account Associate","Denver, CO","Velocity Global","Computer Software","1/26/2026"
"Harrison Gray","Student at University of Denver","Denver, CO","","","1/26/2026"
"Charles Hollie","Team Lead","Denver, CO","Patagonia","Retail","1/26/2026"
"Katrina Schiffer","Project Engineer","Denver, CO","RK Mechanical","Construction","1/26/2026"
"Jaime Sundberg","Hospitality Management Student | Class of 2027","Denver, CO","Fritz Knoebel School of Hospitality Management","Hospitality","1/26/2026"
"Bridget Ebeling","Computer Science & French Major | Graphic Design Minor","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Ben Hogan","Trader 1 Risk Analyst","Denver, CO","Fanatics","Computer Software","1/26/2026"
"Kelsey Christensen","M.S. Biological Science Student | Cell & Molecular Biology Research","United States","University of Denver Natural Sciences & Mathematics","Higher Education","1/26/2026"
"Jeremy Van Denack","Graduate Student | Real Estate & Built Environment","Denver, CO","Toll Brothers","Real Estate","1/26/2026"
"Mateo Mazariego","Environmental Policy Undergraduate Student","Los Angeles, CA","Los Angeles Cleantech Incubator (LACI)","Renewables & Environment","1/26/2026"
"Mary Ringgenberg","Software Engineer","Fort Collins, CO","Anduril Industries","Defense & Space","1/26/2026"
"Joshua Shaw","Business Information & Analytics Student","Kansas City, MO","Jewish Federation of Kansas City","Fundraising","1/26/2026"
"Jaxon Packer","Computer Science & Criminology Student","Denver, CO","Triangle Fraternity","Higher Education","1/26/2026"
"Madelyn Wickless","Criminology Student | Pre-Law Track","Killington, VT","Athleta","Apparel & Fashion","1/26/2026"
"Talya Riciputi","Sociology Major | Leadership Minor","United States","Delta Zeta Sorority","Non-profit Organization Management","1/26/2026"
"Jon Hall","Aspiring Financial Advisor | Student","Denver, CO","Georgia Tech Foundation, Inc.","Higher Education","1/26/2026"
"Elizabeth Haney","Real Estate Finance Student","Omaha, NE","Whole Foods Market","Retail","1/26/2026"
"Sage Williams","Denver Department of Human Services","Denver, CO","City and County of Denver","Government Administration","1/26/2026"
"Lilli Malekzadeh","Psychology Student at the University of Denver","Denver, CO","Cocoa Legato","Food Production","1/26/2026"
"Lianna Almeida","Student at Arizona State University","United States","University of Denver","Higher Education","1/26/2026"
"Penelope Ades","Global Partnerships","Denver, CO","Oak View Group","Entertainment","1/26/2026"
"Theodora Boateng","Theatre | Public Relations | Journalism","Denver, CO","Hollister Co.","Retail","1/26/2026"
"Nathaniel Schott","Recent DU Graduate | Conservationist","Denver, CO","University of Denver Alpine Club","Sports","1/26/2026"
"Maximos Smith","Finance Major | Class of 2025","Denver, CO","Stats Perform","Sports","1/26/2025"
"Jack Stevens","Product Analyst","Denver, CO","DaVita Kidney Care","Hospital & Health Care","1/26/2026"
"Jack Jesaitis","Student at University of Denver","Denver, CO","Crowdfund Capital Advisors","Financial Services","1/26/2026"
"Camille Popiel","Student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Will Thrush","Biochemistry Student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Gabrielle Eckert","Junior Hospitality Student","Parker, CO","Fritz Knoebel School of Hospitality Management","Hospitality","1/26/2026"
"Jason Waldman","EnrollHere","Westwood, NJ","EnrollHere, Inc.","Computer Software","1/26/2026"
"Julianna Crowley","Student at University of Denver","Denver, CO","Gamma Phi Beta International Sorority","Non-profit Organization Management","1/26/2026"
"Ian Warren","Technical Game Designer","Denver, CO","GameU","Computer Games","1/26/2026"
"Michael P. Allen","National Corporate Housing Financial Analyst","Denver Metropolitan Area","National Corporate Housing","Hospitality","1/26/2026"
"Eamon Gillen","Student at University of Denver","Denver, CO","Lula Cocina Mexicana","Restaurants","1/26/2026"
"Kyle Bucholtz","Electrical Engineer at Sierra Nevada Corporation","Denver Metropolitan Area","Sierra Nevada Corporation","Defense & Space","1/26/2026"
"Benjamin LaFontan","Associate at Newmark","New York City Metropolitan Area","Newmark","Real Estate","1/26/2026"
"Holland Moss","Recent Graduate | Phi Beta Kappa Society","Denver, CO","Common Threads Consignment","-","1/26/2026"
"Chip Knapp","Regulatory Finance Accountant | B.S. Finance","Denver, CO","UnitedHealthcare","Hospital & Health Care","1/26/2026"
"Brynn Dale","Environmental Science Student at the University of Denver","Denver, CO","South Suburban Park and Recreation District","Recreational Facilities & Services","1/26/2026"
"Michael Carchidi","Student at University of Denver | Marketing Intern","Denver, CO","Level 1 Productions","Media Production","1/26/2026"
"Christopher Brophy","Student at University of Denver","Denver, CO","Voyager Technologies","Defense & Space","1/26/2026"
"Olivia Broughton","Psychology & Management Student","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Kaylin Francisco","Fourth Year Computer Science Student","Denver, CO","Geek Squad","Information Technology & Services","1/26/2026"
"Dani Holstein","University of Denver Graduate | Geography","Denver, CO","CorePower Yoga","Health, Wellness & Fitness","1/26/2026"
"Isaac Ruderman","Analyst at Deloitte | Graduate of the University of Denver","Denver, CO","Deloitte","Management Consulting","1/26/2026"
"Emma Goldstein","Assistant Director of Athletic Communications","Denver, CO","University of Nebraska at Omaha","Higher Education","1/26/2026"
"Andrea Chu","Student at University of Denver","Denver, CO","University of Denver Natural Sciences & Mathematics","Higher Education","1/26/2026"
"Grayson Passias","Internal Wholesaler – Mutual Funds | Transamerica","Denver, CO","Transamerica","Financial Services","1/26/2026"
"Conor Selfors","Student at the University of Denver | BIA Major","Denver Metropolitan Area","Gamut Ventures","Venture Capital & Private Equity","1/26/2026"
"Colton Neal","Student at the University of Denver Studying Real Estate","Denver, CO","Darcy's Pub Downtown","Restaurants","1/26/2026"
"Michael Logan","Engineering Student at University of Denver","Denver, CO","RK Mechanical","Construction","1/26/2026"
"Matthew Taylor","Game Development & Emergent Digital Practices","Denver, CO","Aramark","Hospitality","1/26/2026"
"Owen Mantelli","Student at University of Denver Studying Political Science, Strategic Communications, and Leadership","Castle Rock, CO","Undergraduate Student Government - University of Denver","Education Management","1/26/2026"
"Brian Pekala","Business and Japanese Student at the University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Riley Bagnato","Student at University of Denver","Denver, CO","United Airlines","Airlines/Aviation","1/26/2026"
"Biruk Damte","Student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Angus Tresnan","Master of Social Work student at University of Denver","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Lauren Roberts","Chemistry and Economics student at University of Denver","Longmont, CO","University of Denver","Higher Education","1/26/2026"
"Ashlyn Fortman","Student at University of Denver","Denver Metropolitan Area","Serenity Healthcare","Mental Health Care","1/26/2026"
"Harkin Liati","Student at University of Denver | Daniels College of Business","Denver, CO","TurnKey Solutions","Construction","1/26/2026"
"Lillian Loudon","International Studies & German Major","Denver, CO","American Transplant Foundation","Hospital & Health Care","1/26/2026"
"Peter Johnson","Business Information and Analytics Student","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Bryanna Reed","JD Candidate 2026 | Sturm Elevation Scholar","Denver Metropolitan Area","University of Denver - Sturm College of Law","Higher Education","1/26/2026"
"Julian Bakewell","Student at University of Denver","Denver, CO","CostaTerra Golf & Ocean Club","Real Estate","1/26/2026"
"Emilia Brown","Student at the University of Denver interested in Economics","Boulder, CO","Marine Layer","Apparel & Fashion","1/26/2026"
"Jack Cambruzzi","Dedicated Student | Entrepreneur","Denver, CO","PanoServ","-","1/26/2026"
"Jadon Scures","Student at University of Denver","Denver, CO","Bukit Interiors","International Trade & Development","1/26/2026"
"A.J. Zhawred","First Year Finance Major","Fairfield, CT","FAIRFIELD BEACH CLUB INC","Civic & Social Organization","1/26/2026"
"Savanna Berry","Pre-PA | Student-Athlete","Denver, CO","NCAA","Higher Education","1/26/2026"
"Zoe Weisenfluh","International Business | Spanish | University of Denver","Denver, CO","Lucile's Creole Cafe","Food & Beverages","1/26/2026"
"Citlaly Armendariz","Finance student at Daniels School of Business","Denver, CO","SEPHORA","Retail","1/26/2026"
"Ayden Smith","Psychology Student | Marketing Minor","Denver, CO","Joy Burns Arena","Health, Wellness & Fitness","1/26/2026"
"Maximo Sanchez","Student at University of Denver","Miami, FL","Linkvest Capital","Financial Services","1/26/2026"
"Ayanna Schubert","International Business and Psychology student","Denver, CO","Birch Psychology","Mental Health Care","1/26/2026"
"Hayes Grimm","Student at University of Denver","Denver, CO","Freedom Boat Club","Recreational Facilities & Services","1/26/2026"
"Libby Evans","Content Marketing Specialist at Pathify","Denver, CO","Pathify","Higher Education","1/26/2026"
"Mirjana V Profeta","Associate","Denver, CO","Novi Strategies","Management Consulting","1/26/2026"
"Michael Donohue","Management Student | Young Professional","Denver, CO","New England Fish Mongers","-","1/26/2026"
"Charlotte Arrix","Marketing Major | Digital Marketing","Denver, CO","Chi Omega - Zeta Mu Chapter","Non-profit Organization Management","1/26/2026"
"Chance Bottcher","Corporate Trainer | Client Representative | DU Graduate","Denver, CO","Oracle Acquisitions","Marketing & Advertising","1/26/2026"
"Kate Rehm","Student at University of Denver- Fritz Knoebel School","Denver, CO","Rockywold Deephaven Camps","Hospitality","1/26/2026"
"Margaret Lawton","Internal Audit and Financial Advisory Consultant","Denver, CO","Protiviti","Management Consulting","1/26/2026"
"Abigail Wineland","Integrated Marketing | Legal Research & Policy Advocacy","Denver, CO","Molly's Spirits","Retail","1/26/2026"
"Mia Genazzi","BA in Sociology | Passionate About Nonprofit","Denver, CO","Gateway180","Individual & Family Services","1/26/2026"
"Elizabeth Navarro","Student and Future Entrepreneur","Denver, CO","Pandora","Luxury Goods & Jewelry","1/26/2026"
"Katie Mattson","International Business, Marketing, and Psychology Student","Naperville, IL","Energy Resources Marketing","Marketing & Advertising","1/26/2026"
"Peter Goodman","Hospitality Management Student","Denver, CO","Fritz Knoebel School of Hospitality Management","Hospitality","1/26/2026"
"Joshua Runck","Student at University of Denver","Denver, CO","The Noel Company, Inc.","Construction","1/26/2026"
"Ava Goyer","College Athlete | Hospitality Student","Denver, CO","Fritz Knoebel School of Hospitality Management","Hospitality","1/26/2026"
"Jenna Garner","Finance & Accounting student","Denver, CO","University of Denver - Daniels College of Business","Higher Education","1/26/2026"
"Edmund Henry","Environmental Project Coordinator","Denver, CO","Quandary Consultants","Environmental Services","1/26/2026"
"Tobias Holme","Bachelor of Arts -- International Studies","Denver, CO","The Borgen Project","Non-profit Organization Management","1/26/2026"
"Jacob Brassard","Building AI People Search RAG","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Ludmila Kuzibaeva","BSBA Candidate in Finance and International Studies 2026","Denver, CO","Deloitte","Management Consulting","1/26/2026"
"Ben Mendenhall","Student at University of Denver","United States","The Church of Jesus Christ of Latter-day Saints","Religious Institutions","1/26/2026"
"Max Pasley","Associate Trader @ Fanatics","Denver, CO","Fanatics","Computer Software","1/26/2026"
"Sarah Dickson","Transportation policy Intern","Denver, CO","Peak Consulting Group LLC","Civil Engineering","1/26/2026"
"Jeremy Richardson","Student at University of Denver","Denver, CO","Car Tech Details","Retail","1/26/2026"
"Benjamin Hyman","Political Science, International Studies, and Chinese student","Denver, CO","University of Denver - Josef Korbel School of Global and Public Affairs","Higher Education","1/26/2026"
"Reed Wuepper","Student at University of Denver","Bend, OR","Ace Hardware Corporation","Retail","1/26/2026"
"Ameya Kartha","Student at the University of Denver","Denver, CO","Empire Des Enfants","Non-profit Organization Management","1/26/2026"
"Hudson Strode","Finance Emphasis | President of DU Club Golf","United States","University of Denver Club Golf","-","1/26/2026"
"Grace Kane","Double Major in Criminology and Psychology","Denver, CO","Boulder County","Government Administration","1/26/2026"
"Hadley Way","Student at University of Denver | Fritz Knoebel Hospitality","Denver, CO","Frasca Hospitality Group","Hospitality","1/26/2026"
"Emely Mier","MA-International Security Candidate","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Truman Esmond","Computer Science Student","Denver, CO","University of Denver - Ritchie School of Engineering & Computer Science","Higher Education","1/26/2026"
"Kelsea Morrison","Finance Major & Econ/Accounting Minors","San Diego, CA","Cherry Hills Country Club","Recreational Facilities & Services","1/26/2026"
"Alma Nielsen","Real Estate Student","Boulder, CO","Rise Against Suicide","Mental Health Care","1/26/2026"
"Elyse Warren","Honors Biology Student | EMT","Denver, CO","University of Denver","Higher Education","1/26/2026"
"Marcus Kaufman","Incoming Analyst at J.P. Morgan Private Bank","Denver, CO","D.A. Davidson Equity Capital Markets","Investment Banking","1/26/2026"
"Luke Thomas","Audit & Assurance Assistant at Deloitte","Denver, CO","Deloitte","Management Consulting","1/26/2026"
"Jake Brudner","Finance @ University of Denver | CFA Challenge Analyst","Denver, CO","Evans Senior Investments [ESI]","Real Estate","1/26/2026"
"Frank Mora","Associate Zone Business Manager at Frito-Lay","Denver, CO","Frito-Lay","Food & Beverages","1/26/2026"
"James Phillips","Graduate Student at the University of Oklahoma","Morrison, CO","Charles Schwab","Financial Services","1/26/2026"
"Brad Schlafer","Multifamily Investment Sales | Institutional Properties","Denver Metropolitan Area","CBRE","Real Estate","1/26/2026"
"Simon H.","Software at SciTec, Inc.","Boulder, CO","SciTec","Defense & Space","1/26/2026"
"Travis Martin","Asset Management Analyst","Denver, CO","Ulysses Development Group","Real Estate","1/26/2026"
"Sam Hallam","Land Development","Denver, CO","Oakwood Homes","Real Estate","1/26/2026"
"Chapman Spaan","Student of The Daniels School of Business","Denver, CO","Indian Hill Country Club","Recreational Facilities & Services","1/26/2026"`;

export const getAlumni = (): AlumniProfile[] => {
  const data = localStorage.getItem(ALUMNI_KEY);
  if (!data) {
    const parsed = parseAlumniCSV(CSV_CONTENT);
    localStorage.setItem(ALUMNI_KEY, JSON.stringify(parsed));
    return parsed;
  }
  return JSON.parse(data);
};

export const saveAlumni = (profiles: AlumniProfile[]) => {
  localStorage.setItem(ALUMNI_KEY, JSON.stringify(profiles));
};

export const addAlumni = (profile: AlumniProfile) => {
  const current = getAlumni();
  saveAlumni([...current, profile]);
};

export const bulkAddAlumni = (profiles: AlumniProfile[]) => {
  const current = getAlumni();
  const uniqueNew = profiles.filter(newP => !current.some(currP => currP.name === newP.name));
  saveAlumni([...current, ...uniqueNew]);
};

export const resetToCSV = () => {
  const parsed = parseAlumniCSV(CSV_CONTENT);
  localStorage.setItem(ALUMNI_KEY, JSON.stringify(parsed));
  return parsed;
};

export const updateAlumni = (profile: AlumniProfile) => {
  const current = getAlumni();
  saveAlumni(current.map(p => p.id === profile.id ? profile : p));
};

export const getInteractions = (alumniId?: string): Interaction[] => {
  const data = localStorage.getItem(INTERACTIONS_KEY);
  const interactions: Interaction[] = data ? JSON.parse(data) : [];
  if (alumniId) {
    return interactions.filter(i => i.alumniId === alumniId);
  }
  return interactions;
};

export const addInteraction = (interaction: Interaction) => {
  const current = getInteractions();
  localStorage.setItem(INTERACTIONS_KEY, JSON.stringify([...current, interaction]));
};

// Chat Persistence Service
export const saveChatState = (messages: ChatMessage[], input: string) => {
  sessionStorage.setItem(CHAT_HISTORY_KEY, JSON.stringify({ messages, input }));
};

export const getChatState = (): { messages: ChatMessage[], input: string } | null => {
  const data = sessionStorage.getItem(CHAT_HISTORY_KEY);
  return data ? JSON.parse(data) : null;
};

export const clearChatState = () => {
  sessionStorage.removeItem(CHAT_HISTORY_KEY);
};
